### ISSUE TITLE
Pause Entity

### ISSUE THREAD

**Issue by safehammad** [Fiona/Myrmidon#29]
Pausing an entity for `x` ticks currently requires the following:

    for frame, total in Game.timer_ticks(x):
        yield

It would be much cleaner and the intention would be more obvious with something like the following:

    Entity.sleep(x)

**Comment by Frimkron** [comment]
What if `yield`ing a number told Myrmidon to stop executing the entity for that many frames?

**Comment by safehammad** [comment]
Something like that would be neat. We could actually do:

```yield self.pause(ticks)```

So:
* It's consistent with the new switch state syntax. 
* It's explicit that we're pausing.
* It allows us to continue to add further as yet unknown yield based operations.

**Comment by Fiona** [comment]
Safe's last two points convinced me to go for the option of
    yield self.pause(ticks)
At the moment you can indeed simply yield an integer and it will function, but that's not super future-proof so I'd recommend against doing it.

**Comment by Frimkron** [comment]
Ok, but I'm not totally convinced that this isn't confusing and doesn't just create a need for unnecessary boilerplate. 

Would yielding an integer still change the entity's state to some kind of pause state, or would `Entity.pause(ticks)` litterally just return the value it is passed?

Generally, I think the convention of yielding the result of changing state is misleading, because the yielded value is ignored. I also feel that creating a special "pause" state, along with a way to jump back to a previous state, is unnecessary when all we're really trying to do is yield multiple times.
